# Generated by Django 4.2.8 on 2026-04-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails_backend', '0003_user_address_user_birthday_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELED', 'Đã hủy')], default='PENDING', max_length=15),
        ),
    ]
